using System.Collections.Generic; using System.IO; using UnityEngine; using UnityEngine.UIElements;
public class ScreenLoader:MonoBehaviour {
 [SerializeField] private UIDocument uiDocument; [SerializeField] private float refreshRateHz=20f;
 public ScreenDefinition CurrentScreen{get;private set;}
 readonly List<IRuntimeWidget> runtimeWidgets=new List<IRuntimeWidget>(); readonly AddonStyleRuntime styleRuntime=new AddonStyleRuntime();
 VisualElement documentRoot,currentScreenContainer; float nextRefreshTime;
 void Awake(){if(uiDocument==null){Debug.LogError("ScreenLoader requires a UIDocument reference.");enabled=false;return;}documentRoot=uiDocument.rootVisualElement;}
 void Update(){if(refreshRateHz<=0f||Time.unscaledTime<nextRefreshTime)return;nextRefreshTime=Time.unscaledTime+(1f/refreshRateHz);foreach(IRuntimeWidget w in runtimeWidgets)w.Refresh();}
 public void LoadAddonScreen(string addonId,string screenId){if(!AddonRegistry.TryGetScreen(addonId,screenId,out LoadedAddon addon,out AddonScreenEntry entry)){Debug.LogError("Addon screen not found: "+addonId+" / "+screenId);return;}if(string.IsNullOrWhiteSpace(entry.path)){Debug.LogError("Screen path is empty for: "+addonId+" / "+screenId);return;}LoadScreenFromFolder(addonId,screenId,addon.RootPath,Path.Combine(addon.RootPath,entry.path));}
 void LoadScreenFromFolder(string addonId,string screenId,string addonRoot,string folder){string screenPath=Path.Combine(folder,"screen.json");if(!File.Exists(screenPath)){Debug.LogError("Screen file not found: "+screenPath);return;}try{CurrentScreen=ScreenDefinition.FromJson(File.ReadAllText(screenPath));}catch(System.Exception ex){Debug.LogError("Invalid screen definition: "+screenPath+" | "+ex.Message);return;}if(CurrentScreen==null||CurrentScreen.Widgets==null){Debug.LogError("Invalid screen definition: "+screenPath);return;}string stylePath=string.IsNullOrWhiteSpace(CurrentScreen.Style)?null:Path.Combine(folder,CurrentScreen.Style);if(!styleRuntime.Load(stylePath))Debug.LogWarning("Screen will continue without external styles.");BuildScreen(addonId,addonRoot);Debug.Log("[SCREEN OK] "+addonId+" / "+screenId+" -> "+CurrentScreen.Title+" ("+CurrentScreen.Widgets.Count+" widgets)");}
 void BuildScreen(string addonId,string addonRoot){runtimeWidgets.Clear();if(currentScreenContainer!=null)currentScreenContainer.RemoveFromHierarchy();currentScreenContainer=new VisualElement();currentScreenContainer.name="screen-"+CurrentScreen.Id;currentScreenContainer.AddToClassList("screen-root");currentScreenContainer.AddToClassList("addon-"+Sanitize(addonId));currentScreenContainer.style.position=Position.Absolute;currentScreenContainer.style.left=0;currentScreenContainer.style.top=0;currentScreenContainer.style.right=0;currentScreenContainer.style.bottom=0;documentRoot.Add(currentScreenContainer);var context=new WidgetContext{AddonRootPath=addonRoot,Styles=styleRuntime};foreach(WidgetDefinition d in CurrentScreen.Widgets)BuildTree(d,context,currentScreenContainer,true);styleRuntime.ApplyRecursive(currentScreenContainer);}
 void BuildTree(WidgetDefinition d,WidgetContext c,VisualElement parent,bool topLevel){IRuntimeWidget w=WidgetFactory.Create(d,c);if(w==null)return;VisualElement e=w.Root;if(!string.IsNullOrWhiteSpace(d.Id))e.name=d.Id;if(!string.IsNullOrWhiteSpace(d.StyleClass))e.AddToClassList(d.StyleClass);if(topLevel&&d.Layout!=null)ApplyLayout(e,d.Layout);parent.Add(e);runtimeWidgets.Add(w);if(d.Children!=null)foreach(WidgetDefinition child in d.Children)BuildTree(child,c,e,false);}
 static void ApplyLayout(VisualElement e,WidgetLayout l){const float cellWidth=180f,cellHeight=110f,gap=12f;e.style.position=Position.Absolute;e.style.left=l.X*(cellWidth+gap);e.style.top=l.Y*(cellHeight+gap);e.style.width=l.Width*cellWidth+(l.Width-1)*gap;e.style.height=l.Height*cellHeight+(l.Height-1)*gap;}
 static string Sanitize(string v)=>string.IsNullOrWhiteSpace(v)?"unknown":v.Replace(".","-").Replace("_","-").Replace(" ","-").ToLowerInvariant();
}
